spring.application.name=RSAssigment
spring.data.mongodb.uri=mongodb+srv://admin:hVewY5ETDDFwRBDE@cluster0.1jjbd.mongodb.net/ReviewsDB?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=ReviewsDB