spring.application.name=RSAssigment
spring.data.mongodb.uri=mongodb+srv://nathanw:Collegepassw0rd1!@cluster0.5qx6v.mongodb.net/?retryWrites=true&w=majority&appName=ReviewDB
spring.data.mongodb.database=Cluster0